### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by buzhongyaoname** [matao1984/vec-map#1]
Hey，matao1984
  Thanks for your great job. I want to know the principle you calculation the displancement.  Do you get the ideal coordinates of the central atom by calculating the coordinates of the vertices of the quadrilateral system? Finally, the ideal coordinates of the center are compared with the actual coordinates.
  Or you use IFFT to get the ideal coordinates of the atom and then compare them with the actual atomic coordinates.
  Finally, whether your algorithm is suitable for hexagonal and rhomboidal ferroelectric materials.
                                
                                                                                                                                                  Thanks

**Comment by matao1984** [comment]
Hi buzhongyaoname,
This tool finds the atom positions with 2D Gaussian fitting. The displacement vectors are calculated by comparing the actual position and the geometric center of the four neighboring atoms. I did not use the IFFT method. This tool is designed specifically for distorted perovskite structures. Though in crystallography some materials are defined as hexagonal, or tetragonal, or rhombohedral, or orthorombic, as long as they are derived from the perovskite structure, the algorithm should work for all type of ferroelectric/antiferroelectric materials with the perovskite structure.

**Comment by buzhongyaoname** [comment]
Thanks for your answer. It is a great tool for perovskite structures. It is a pity that the antiferroelectric materials I studied are not perovskite structures.
