### ISSUE TITLE
hyperspy atomap version

### ISSUE THREAD

**Issue by w6765579** [matao1984/vec-map#2]
Thanks for the tool. 

I would like to know whether there is requirement for the version of hyperspy and atomap. I have install both, however, it still report hyperspy error.

Thanks.

**Comment by matao1984** [comment]
I have tested hyperspy 1.7.0 and atomap 0.3.2. Can you post the error messages? To avoid strange issues you have to create a virtual environment for the vecmap and run the pip installer.

**Comment by w6765579** [comment]
Thanks for the reply. 

Actually I installed it in the linux shell environment correctly. However, it reported a "libstdc++.so.6" error when I ran it. Then I thought it was propable an environment problem.  Then I tried to install it into a specific virtual environment. Then I came across the hyperspy problem. I tried several versions of hyperspy 1.7.0 and 1.7.1, installed both in the shell environment or base virtural environment, and they are all not okay when I tried to install vec-map on its specific vec-map virtual environment with the hyperspy error. And I can not install any hyperspy in the vec-map virtual environment when I made this try. 

Today, I found when I ran anaconda-navigator, the  "libstdc++.so.6" error also pop up. Then I realized that this error may not be an error for vec-map. When I solved the "libstdc++.so.6" error, the vec-map worked even I installed it in the linux shell environment. 

However, when I opened vec-map, I found it seemed to be used for the experimental TEM recognition. Am I right? If I would like to use it in the theoretical calculated structure such as cif file, is it possible?

Thanks.

**Comment by matao1984** [comment]
Glad you have the problem sorted out. The tool was designed for TEM images, both simulated and experimental. It cannot take structure files like cif. I did not understand your needs on those structures. If you want to just measure the displacement from the calculated structures you'd better use other tools like Crystal Maker or Vesta. If you really want to use the vec-map, you can try to simulate TEM images from your cif files. However, it really sounds like a detour.

**Comment by w6765579** [comment]
Thanks. I actually would like to do displacement statistics for the cif stucture. However, I may introduce this tool to my experimental collegues.
